services:
  - type: web
    name: hiresmart-ai
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: free
    autoDeploy: true
    envVars:
      - key: APP_NAME
        value: "HireSmart AI"
      - key: APP_ENV
        value: "production"
      - key: APP_DEBUG
        value: "false"
      - key: LOG_CHANNEL
        value: "stderr"
      - key: CACHE_STORE
        value: "file"
      - key: QUEUE_CONNECTION
        value: "sync"
      - key: SESSION_DRIVER
        value: "file"
      - key: APP_KEY
        value: "base64:aB/8R6bWPx0utUhlrOZlCciTIIWe6Tx34HVMJq0avNY="
      - key: APP_URL
        value: "https://hiresmart-ai.onrender.com"
      - key: DB_CONNECTION
        value: "pgsql"
      - key: DB_URL
        sync: false
      - key: RUN_MIGRATIONS
        value: "true"
